# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishtime', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('wechat', models.CharField(blank=True, max_length=30)),
                ('qq', models.IntegerField(blank=True, null=True)),
                ('imgabout', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
